### PR TITLE
files were not according to chapter numbers

### PR DESCRIPTION
**Pull request by Mehebub24**

### CODE REVIEW

**Comment by clarksmr** [comment]
Hm, I don't really understand this PR. 
- The first change in it, for example, renames `chapter8.ml` to `chapter10.ml`. But, there is no chapter 10 in the textbook. 
- And looking at the changes to `chapter4.ml`, the solution to `sum_cube_odd` has been deleted. Looks like maybe some others, too?

Could you provide more information about why these changes should be made? Thank you!

**Comment by Mehebub24** [comment]
> * The first change in it, for example, renames `chapter8.ml` to `chapter10.ml`. But, there is no chapter 10 in the textbook.
But in this book( https://cs3110.github.io/textbook/ocaml_programming.pdf  ) there are 13 chapters

**Comment by Mehebub24** [comment]
The first change in it, for example, renames chapter8.ml to chapter10.ml. But, there is no chapter 10 in the textbook.
>>But according to this book( https://cs3110.github.io/textbook/ocaml_programming.pdf ) there are 14 chapters

**Comment by cionx** [comment]
This is a discrepancy between the only version (https://cs3110.github.io/textbook/cover.html) and the PDF version (https://cs3110.github.io/textbook/ocaml_programming.pdf). The online version doesn’t number the preface, the chapter about the Curry–Howard correspondence, and the appendices. The PDF version numbers all chapters.

It seems to me that the numbering in the online version is deliberate, whereas the one in the PDF version is automatically generated. This would make it a flaw in the PDF version.

**Comment by Mehebub24** [comment]
apology for my misunderstand

**Comment by Mehebub24** [comment]
Apologies for my misunderstanding

**Comment by clarksmr** [comment]
Ah, thanks for explaining. I'll go ahead and close this PR without merging. If you want to submit something else later (e.g. if you had some corrections to solutions), please feel free to open a new PR.

Meanwhile I've filed an [issue about PDF chapter numbers](https://github.com/cs3110/textbook/issues/154) in the main textbook repo.

**Comment by clarksmr** [comment]
Ah, thanks for explaining. I'll go ahead and close this PR without merging. If you want to submit something else later (e.g. if you had some corrections to solutions), please feel free to open a new PR.

Meanwhile I've filed an [issue about PDF chapter numbers](https://github.com/cs3110/textbook/issues/154) in the main textbook repo.

**Pull request closed without merging**
